apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: ezraone/udagram-frontend:v3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      restartPolicy: Always

