apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend